/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laundrypbo.apps.view;

import laundrypbo.apps.aboutUs.AboutAldi;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import laundrypbo.apps.controller.AboutController;
import laundrypbo.apps.model.LaundryModel;
import laundrypbo.apps.view.LaundryMainView;

/**
 *
 * @author Aldiansyah
 */
public class AboutView extends javax.swing.JFrame {
/** Creates new form LoginView */
    private AboutController controller;
    private AboutAldi aboutAldi;
    
    public AboutView() {
        controller = new AboutController();
        aboutAldi = new AboutAldi();

        // model.setFormLoginListener(this);

        initComponents();
  }

     public JPanel getViewAbout() {
        return ViewAbout;
    }
     
      public JPanel getAboutPanel() {
        return aboutPanel;
    }
     
    
     public JPanel getAboutMenu() {
        return aboutMenu;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutPanel = new javax.swing.JPanel();
        aboutMenu = new javax.swing.JPanel();
        btnAboutAli = new javax.swing.JButton();
        btnAboutAldi = new javax.swing.JButton();
        btnAboutAdni = new javax.swing.JButton();
        btnAboutAzka = new javax.swing.JButton();
        btnAboutYuan = new javax.swing.JButton();
        ViewAbout = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        AdniPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aboutPanel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        aboutPanel.setPreferredSize(new java.awt.Dimension(920, 780));
        aboutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aboutMenu.setBackground(new java.awt.Color(255, 76, 48));

        btnAboutAli.setText("ALI");
        btnAboutAli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutAliMouseClicked(evt);
            }
        });
        btnAboutAli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutAliActionPerformed(evt);
            }
        });

        btnAboutAldi.setText("ALDI");
        btnAboutAldi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutAldiMouseClicked(evt);
            }
        });

        btnAboutAdni.setText("ADNI");
        btnAboutAdni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutAdniMouseClicked(evt);
            }
        });
        btnAboutAdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutAdniActionPerformed(evt);
            }
        });

        btnAboutAzka.setText("AZKA");
        btnAboutAzka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutAzkaMouseClicked(evt);
            }
        });
        btnAboutAzka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutAzkaActionPerformed(evt);
            }
        });

        btnAboutYuan.setText("YUAN");
        btnAboutYuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutYuanMouseClicked(evt);
            }
        });
        btnAboutYuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutYuanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutMenuLayout = new javax.swing.GroupLayout(aboutMenu);
        aboutMenu.setLayout(aboutMenuLayout);
        aboutMenuLayout.setHorizontalGroup(
            aboutMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAboutAdni, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnAboutAldi, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAboutAli, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnAboutAzka, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAboutYuan, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        aboutMenuLayout.setVerticalGroup(
            aboutMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(aboutMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAboutYuan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAboutAzka, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAboutAli, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAboutAldi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAboutAdni, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        aboutPanel.add(aboutMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        ViewAbout.setPreferredSize(new java.awt.Dimension(221, 184));
        ViewAbout.setLayout(new java.awt.CardLayout());

        AdniPanel.setPreferredSize(new java.awt.Dimension(920, 780));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("TTL      : Batam, 06 - September - 2003");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Konstribusi:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("NO HP : 081936816852");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("NIM     : 10121179");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("NAMA  : MUHAMMAD ADNI TILLA GUMILANG");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundrypbo/resources/img/adni.jpg"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("EMAIL : adni.10121179@mahasiswa.unikom.ac.id");

        javax.swing.GroupLayout AdniPanelLayout = new javax.swing.GroupLayout(AdniPanel);
        AdniPanel.setLayout(AdniPanelLayout);
        AdniPanelLayout.setHorizontalGroup(
            AdniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdniPanelLayout.createSequentialGroup()
                .addGroup(AdniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdniPanelLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel1))
                    .addGroup(AdniPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(AdniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdniPanelLayout.setVerticalGroup(
            AdniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdniPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        ViewAbout.add(jPanel1, "card2");

        aboutPanel.add(ViewAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 80, 914, 730));

        getContentPane().add(aboutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 594));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAboutAliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutAliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAboutAliActionPerformed

    private void btnAboutAdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutAdniActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnAboutAdniActionPerformed

    private void btnAboutAdniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutAdniMouseClicked
        // TODO add your handling code here:
       controller.menuAdni(this);
    }//GEN-LAST:event_btnAboutAdniMouseClicked

    private void btnAboutAldiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutAldiMouseClicked
        // TODO add your handling code here:
        controller.menuAldi(this);       
    }//GEN-LAST:event_btnAboutAldiMouseClicked

    private void btnAboutAliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutAliMouseClicked
        // TODO add your handling code here:
        controller.menuAli(this);
    }//GEN-LAST:event_btnAboutAliMouseClicked

    private void btnAboutAzkaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutAzkaMouseClicked
        // TODO add your handling code here:
        controller.menuAzka(this);
    }//GEN-LAST:event_btnAboutAzkaMouseClicked

    private void btnAboutYuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutYuanMouseClicked
        // TODO add your handling code here:
        controller.menuYuan(this);
    }//GEN-LAST:event_btnAboutYuanMouseClicked

    private void btnAboutYuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutYuanActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_btnAboutYuanActionPerformed

    private void btnAboutAzkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutAzkaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAboutAzkaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Metal".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new LoginView().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdniPanel;
    private javax.swing.JPanel ViewAbout;
    private javax.swing.JPanel aboutMenu;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JButton btnAboutAdni;
    private javax.swing.JButton btnAboutAldi;
    private javax.swing.JButton btnAboutAli;
    private javax.swing.JButton btnAboutAzka;
    private javax.swing.JButton btnAboutYuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables





}
