/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundrypbo.apps.view;

import javax.swing.JPanel;

/**
 *
 * @author aliazhar
 */
public class AddView extends javax.swing.JFrame {

    /**
     * Creates new form addView
     */
    public AddView() {
        initComponents();
    }

    public JPanel getAddPanel() {
        return addPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAddNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboAddLayanan = new javax.swing.JComboBox<>();
        txtAddBerat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddTglMasuk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAddReset = new javax.swing.JButton();
        btnAddSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addPanel.setPreferredSize(new java.awt.Dimension(920, 870));
        addPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Buat Transaksi");
        addPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Nama");
        addPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        txtAddNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddNama.setPreferredSize(new java.awt.Dimension(230, 32));
        addPanel.add(txtAddNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Layanan");
        addPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        comboAddLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboAddLayanan.setPreferredSize(new java.awt.Dimension(180, 32));
        addPanel.add(comboAddLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        txtAddBerat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddBerat.setPreferredSize(new java.awt.Dimension(130, 32));
        addPanel.add(txtAddBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Berat (Kg)");
        addPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txtAddTglMasuk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddTglMasuk.setPreferredSize(new java.awt.Dimension(150, 32));
        addPanel.add(txtAddTglMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Tanggal Masuk");
        addPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        btnAddReset.setText("Reset");
        btnAddReset.setPreferredSize(new java.awt.Dimension(100, 31));
        btnAddReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddResetMouseClicked(evt);
            }
        });
        addPanel.add(btnAddReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        btnAddSave.setText("Tambah");
        btnAddSave.setPreferredSize(new java.awt.Dimension(100, 31));
        btnAddSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddSaveMouseClicked(evt);
            }
        });
        addPanel.add(btnAddSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        getContentPane().add(addPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddSaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddSaveMouseClicked

    private void btnAddResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddResetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddResetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton btnAddReset;
    private javax.swing.JButton btnAddSave;
    private javax.swing.JComboBox<String> comboAddLayanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAddBerat;
    private javax.swing.JTextField txtAddNama;
    private javax.swing.JTextField txtAddTglMasuk;
    // End of variables declaration//GEN-END:variables
}
