/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundrypbo.apps.view;

import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;
import laundrypbo.apps.controller.LaundryController;
import laundrypbo.apps.model.LaundryModel;

/**
 *
 * @author aliazhar
 */
public class UbahView extends javax.swing.JFrame {

    /**
     * Creates new form addView
     */
    private LaundryModel model;
   // private AddController controller;
    private LaundryController controller;
    private LaundryMainView mainView;

    public UbahView(LaundryMainView mainView) {
        model = new LaundryModel();
        controller = new LaundryController();
        this.mainView = mainView;
        controller.setModel(model);

        initComponents();
    }

    public JPanel getUbahPanel() {
        return UbahPanel;
    }

    private UbahView() {
        
    }

    public LaundryMainView getMainView() {
        return mainView;
    }

    public JPanel getAddPanel() {
        return UbahPanel;
    }

    public JComboBox<String> getComboAddLayanan() {
        return comboAddLayanan;
    }

    public JTextField getTxtAddBerat() {
        return txtAddBerat;
    }

    public JTextField getTxtAddNama() {
        return txtAddNama;
    }

    public JTextField getTxtAddTglMasuk() {
        return txtAddTglMasuk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UbahPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAddNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboAddLayanan = new javax.swing.JComboBox<>();
        txtAddBerat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddTglMasuk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAddReset = new javax.swing.JButton();
        btnAddSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UbahPanel.setPreferredSize(new java.awt.Dimension(920, 870));
        UbahPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Edit Pelanggan");
        UbahPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Nama");
        UbahPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        txtAddNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddNama.setPreferredSize(new java.awt.Dimension(230, 32));
        UbahPanel.add(txtAddNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Layanan");
        UbahPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        comboAddLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "Kilat" }));
        comboAddLayanan.setPreferredSize(new java.awt.Dimension(180, 32));
        UbahPanel.add(comboAddLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        txtAddBerat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddBerat.setPreferredSize(new java.awt.Dimension(130, 32));
        UbahPanel.add(txtAddBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Berat (Kg)");
        UbahPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txtAddTglMasuk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddTglMasuk.setPreferredSize(new java.awt.Dimension(150, 32));
        UbahPanel.add(txtAddTglMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Tanggal Masuk");
        UbahPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        btnAddReset.setText("Reset");
        btnAddReset.setPreferredSize(new java.awt.Dimension(100, 31));
        btnAddReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddResetMouseClicked(evt);
            }
        });
        UbahPanel.add(btnAddReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        btnAddSave.setText("Tambah");
        btnAddSave.setPreferredSize(new java.awt.Dimension(100, 31));
        btnAddSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddSaveMouseClicked(evt);
            }
        });
        UbahPanel.add(btnAddSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        getContentPane().add(UbahPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddSaveMouseClicked
        // TODO add your handling code here:
        controller.saveAdd(this);
    }//GEN-LAST:event_btnAddSaveMouseClicked

    private void btnAddResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddResetMouseClicked
        // TODO add your handling code here:
        controller.resetAdd(this);
    }//GEN-LAST:event_btnAddResetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UbahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UbahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UbahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UbahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UbahView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UbahPanel;
    private javax.swing.JButton btnAddReset;
    private javax.swing.JButton btnAddSave;
    private javax.swing.JComboBox<String> comboAddLayanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAddBerat;
    private javax.swing.JTextField txtAddNama;
    private javax.swing.JTextField txtAddTglMasuk;
    // End of variables declaration//GEN-END:variables
}
